In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import sweetviz as sv
import dtale

import config

# 最大表示列数の指定（ここでは50列を指定）
pd.set_option("display.max_columns", 50)

In [2]:
# 1.1.0
df_cna = pd.read_table(config.RAW_BRCA_METABRIC_DIR + "/data_cna.txt", index_col=0).T
df_cna = df_cna.drop(df_cna.index[0])

# 1.1.2
df_methylation_promoters_rrbs = pd.read_table(
    config.RAW_BRCA_METABRIC_DIR + "/data_methylation_promoters_rrbs.txt", index_col=0
).T

# 1.1.3
df_mrna_agilent_microarray_zscores_ref_all_samples = pd.read_table(
    config.RAW_BRCA_METABRIC_DIR
    + "/data_mrna_agilent_microarray_zscores_ref_all_samples.txt",
    index_col=0,
).T
df_mrna_agilent_microarray_zscores_ref_all_samples = (
    df_mrna_agilent_microarray_zscores_ref_all_samples.drop(
        df_mrna_agilent_microarray_zscores_ref_all_samples.index[0]
    )
)

# 1.1.4
df_mrna_agilent_microarray = pd.read_table(
    config.RAW_BRCA_METABRIC_DIR + "/data_mrna_agilent_microarray.txt", index_col=0
).T
df_mrna_agilent_microarray = df_mrna_agilent_microarray.drop(
    df_mrna_agilent_microarray.index[0]
)
# 1.1.5
# 要修正・確認

In [3]:
print(df_cna.shape)
df_cna.sort_index().head()

(2173, 22544)

Hugo_Symbol,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2MP1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AACSP1,AADAC,AADACL2,AADACL3,AADACL4,AADAT,AAED1,AAGAB,AAK1,AAMDC,AAMP,AANAT,AAR2,...,ZSCAN4,ZSCAN5A,ZSCAN5B,ZSCAN9,ZSWIM1,ZSWIM2,ZSWIM3,ZSWIM4,ZSWIM5,ZSWIM6,ZSWIM7,ZSWIM8,ZSWIM8-AS1,ZUFSP,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
MB-0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MB-0002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,-1.0,-1.0,0.0,...,0.0,0.0,0.0,-1.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0
MB-0005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0
MB-0006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
MB-0008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,0.0,1.0,-1.0,-1.0,0.0,-1.0,0.0

In [4]:
print(df_methylation_promoters_rrbs.shape)
df_methylation_promoters_rrbs.sort_index().head()

(1418, 13188)

Hugo_Symbol,A2M,A4GALT,AAAS,AACS,AADACL2,AADAT,AAGAB,AAK1,AAMDC,AAMP,AANAT,AAR2,AARS,AARS2,AASDH,AASS,AATK,ABAT,ABCA1,ABCA17P,ABCA2,ABCA3,ABCA7,ABCB10,ABCB4,...,ZSCAN1,ZSCAN12,ZSCAN16,ZSCAN18,ZSCAN2,ZSCAN20,ZSCAN22,ZSCAN25,ZSCAN30,ZSCAN31,ZSCAN32,ZSWIM2,ZSWIM3,ZSWIM4,ZSWIM5,ZSWIM6,ZSWIM7,ZSWIM8,ZUFSP,ZW10,ZWINT,ZXDC,ZYG11B,ZYX,ZZEF1
MB-0006,0.045031,0.017582,0.0,0.000000,0.870370,0.012829,0.000786,0.0,0.000000,0.000000,0.000000,0.024845,0.0,0.000000,0.0,0.003626,0.000000,0.006309,0.019417,0.000000,0.012270,0.368881,0.000000,0.000985,0.222656,...,0.000000,0.100457,0.000000,0.000000,0.001152,0.000941,0.000000,0.001012,0.002096,0.000000,0.000000,0.041176,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.438356,0.000000,0.0,0.000000,0.0,0.013445,0.002770
MB-0028,0.066532,0.038095,0.0,0.019802,0.958763,0.049046,0.003300,0.0,0.008511,0.010772,0.008000,0.229885,0.0,0.011364,0.0,0.009804,0.021472,0.011538,0.171429,0.007059,0.000000,0.324963,0.004866,0.006584,0.303523,...,0.020161,0.704545,0.000000,0.014327,0.012882,0.008439,0.018182,0.002933,0.019190,0.006757,0.011182,0.031746,0.004065,0.007605,0.000000,0.008759,0.008639,0.004717,0.290323,0.024096,0.0,0.000000,0.0,0.008097,0.004566
MB-0035,0.015487,0.033333,0.0,0.000000,0.987395,0.084432,0.002510,0.0,0.000000,0.000000,0.002635,0.000000,0.0,0.000000,0.0,0.027473,0.013514,0.002525,0.348485,0.000000,0.000000,0.407871,0.000000,0.001127,0.586397,...,0.000000,0.810924,0.003344,0.005618,0.003279,0.000000,0.000000,0.010073,0.000000,0.343949,0.001761,0.798165,0.001942,0.000000,0.002639,0.000000,0.000000,0.000000,0.296610,0.000000,0.0,0.000000,0.0,0.000000,0.000000
MB-0046,0.102439,0.000000,0.0,0.000000,0.965517,0.019714,0.000000,0.0,0.000000,0.000000,0.002683,0.047059,0.0,0.000000,0.0,0.000000,0.013699,0.038610,0.254902,0.003044,0.004785,0.360360,0.000000,0.002446,0.247525,...,0.000000,0.493421,0.000000,0.000000,0.000000,0.000000,0.000000,0.004608,0.000000,0.000000,0.000000,0.092486,0.000000,0.000000,0.001488,0.000000,0.002950,0.000000,0.367647,0.000000,0.0,0.002331,0.0,0.000000,0.000000
MB-0050,0.001905,0.009804,0.0,0.000000,0.969231,0.011321,0.000895,0.0,0.000000,0.001087,0.002516,0.057471,0.0,0.000000,0.0,0.020672,0.000000,0.025641,0.082645,0.002857,0.000000,0.326279,0.021097,0.001456,0.211470,...,0.042735,0.175676,0.000000,0.005128,0.002356,0.002141,0.000000,0.001953,0.003448,0.007109,0.000000,0.101449,0.001391,0.000000,0.000000,0.001894,0.000000,0.000000,0.135338,0.000000,0.0,0.000000,0.0,0.000000,0.000000

In [5]:
print(df_mrna_agilent_microarray.shape)
df_mrna_agilent_microarray.sort_index().head()

(1904, 24368)

Hugo_Symbol,RERE,RNF165,CD049690,BC033982,PHF7,CIDEA,PAPD4,AI082173,SLC17A3,SDS,ATP6V1C2,F3,FAM71C,AK055082,BU687559,LIN52,PCOTH,GRM1,FXN,SLC9A1,PML,CR749394,CD164,DB337918,MOBKL2A,...,TMEM146,SLIT3-AS1,PSMC3IP,TEAD1,LOC253724,BM725158,GRHPR,EGLN2,TBC1D4,ANGPTL2,AF086457,AK124197,ENOX1,SBF2-AS1,VN1R4,BX115874,BX107598,UGCGL1,VPS72,CSMD3,CC2D1A,CB986545,IGSF9,DA110839,FAM71A
MB-0000,9.738092,6.469688,5.457135,5.106495,5.652674,11.558869,8.340484,5.384699,5.648494,5.336235,5.468668,7.070649,5.477154,5.489805,5.318898,6.811309,5.440853,5.361170,5.823306,8.809831,6.790593,5.595347,6.141047,5.481023,6.499117,...,5.353135,5.198876,5.901473,5.610397,5.515762,5.213511,8.139151,10.232505,7.311327,9.677952,5.318426,5.635153,5.918239,5.295203,5.474224,5.329883,5.745324,7.021679,8.010657,5.299815,6.235804,5.349555,5.947404,5.615147,5.133576
MB-0002,9.013876,5.748717,5.699735,5.419119,5.611212,6.199492,8.341091,5.490558,5.789506,5.700974,5.495295,6.098949,5.589824,5.055598,5.489397,6.952007,5.545206,5.579463,6.341935,9.307305,6.132436,5.328097,6.400910,5.531249,7.178274,...,4.888335,5.615278,6.447777,5.950548,5.502117,5.124030,8.261487,10.186566,6.324112,8.895600,5.345262,6.281727,5.515844,5.442257,5.303871,5.384794,5.285060,7.612797,7.988643,5.194247,6.328059,5.469445,6.938685,5.231857,5.604560
MB-0005,7.963493,5.553056,5.472386,5.265556,5.793398,6.489781,8.862815,5.538854,5.566713,7.233671,5.537530,6.964546,5.255454,5.374815,5.668776,6.480061,5.790445,5.462634,5.807004,8.477327,5.572601,5.539776,8.575001,5.562090,6.469047,...,5.313808,5.508167,6.076896,5.747801,5.368297,5.371385,7.731911,9.954702,7.222594,8.972083,5.420388,5.404494,5.350242,5.368716,5.370394,5.336455,5.452393,6.619220,8.044471,5.306294,6.306927,5.362207,7.397672,5.372138,5.645597
MB-0006,8.177157,5.391160,5.529795,5.011812,5.807604,5.319779,8.693784,5.430685,5.539252,6.124384,6.657355,6.409554,5.289307,5.299305,5.112324,5.987913,5.393475,5.282728,5.985588,8.101386,5.808433,5.345124,9.164529,5.336013,6.487679,...,5.228991,5.324400,5.650472,5.579526,5.303998,5.351482,8.301195,10.088769,7.053031,8.664307,5.370416,5.480761,5.650978,5.295628,5.694697,5.663304,5.529928,6.966482,7.527300,5.197607,6.515638,5.309927,6.175716,5.586521,5.354582
MB-0008,8.050127,5.530582,5.303667,5.149618,5.934570,8.787583,8.055626,5.239388,5.646685,7.155642,5.878104,5.798117,5.297733,5.610297,5.141883,6.675580,6.598310,5.328773,6.200995,9.301414,6.182025,5.384272,5.904271,5.457066,6.426740,...,5.322069,5.136661,6.403137,5.904885,5.473140,5.460753,8.007261,11.244345,5.926732,8.141539,5.217030,5.442109,5.527755,5.192858,5.474929,5.799346,5.597297,6.942461,8.115359,5.254136,6.323751,5.518767,6.272568,5.204630,5.030636

In [6]:
print(df_mrna_agilent_microarray_zscores_ref_all_samples.shape)
df_mrna_agilent_microarray_zscores_ref_all_samples.sort_index().head()

(1904, 24368)

Hugo_Symbol,RERE,RNF165,CD049690,BC033982,PHF7,CIDEA,PAPD4,AI082173,SLC17A3,SDS,ATP6V1C2,F3,FAM71C,AK055082,BU687559,LIN52,PCOTH,GRM1,FXN,SLC9A1,PML,CR749394,CD164,DB337918,MOBKL2A,...,TMEM146,SLIT3-AS1,PSMC3IP,TEAD1,LOC253724,BM725158,GRHPR,EGLN2,TBC1D4,ANGPTL2,AF086457,AK124197,ENOX1,SBF2-AS1,VN1R4,BX115874,BX107598,UGCGL1,VPS72,CSMD3,CC2D1A,CB986545,IGSF9,DA110839,FAM71A
MB-0000,1.3762,0.1172,0.2469,-1.2960,-0.9217,3.8334,0.2327,0.5466,0.3946,-2.2565,-0.2895,2.2327,0.5461,0.5833,0.0860,1.8587,-0.7744,-0.0783,-1.8107,-1.0442,0.0643,1.4834,0.0505,0.6048,-1.2169,...,0.4823,-1.2252,-0.6151,0.5585,1.0196,-0.9220,0.2225,-1.1379,0.9536,1.5148,-0.8533,-0.7522,1.6283,-1.2388,0.3170,-0.6222,1.5451,-1.1909,-0.4725,-0.1735,-0.3961,0.3665,-1.6152,1.6121,-0.7582
MB-0002,-0.0226,-0.9290,1.9792,1.0040,-1.0580,-0.1394,0.2341,1.3361,1.3907,-1.4654,-0.2331,0.3193,1.5094,-2.4344,1.3107,2.2304,-0.4856,1.4402,0.5351,-0.1628,-1.1188,-0.3540,0.5420,1.0041,0.7800,...,-3.3594,1.7740,0.8200,2.3542,0.9213,-1.6302,0.5591,-1.2160,-1.0666,0.7127,-0.6788,1.0632,-0.1851,-0.0826,-0.9186,-0.4192,-1.1942,0.0247,-0.5276,-0.4878,-0.0706,1.2126,-0.0789,-1.1503,1.2770
MB-0005,-2.2425,-1.2323,0.3577,-0.1114,-0.4655,0.1429,1.3516,1.6920,-0.1929,1.4458,-0.1441,2.0353,-1.3994,-0.1958,2.5649,0.9565,0.1754,0.6339,-1.8873,-1.6586,-2.2144,1.1075,4.0836,1.2478,-1.3095,...,0.1683,1.0210,-0.1422,1.2947,-0.0543,0.3030,-0.9314,-1.6151,0.7821,0.7938,-0.1940,-1.4430,-0.9642,-0.6574,-0.4322,-0.5978,-0.1758,-2.0710,-0.3882,-0.1544,-0.1448,0.4565,0.5685,-0.1200,1.4474
MB-0006,-1.7706,-1.4902,0.7725,-2.0158,-0.4199,-1.0699,0.9961,0.8912,-0.3918,-0.5995,2.0267,0.9580,-1.0979,-0.7150,-1.4428,-0.4605,-0.9071,-0.6368,-1.0581,-2.3798,-1.7419,-0.2346,4.9051,-0.5657,-1.2521,...,-0.5155,-0.3004,-1.3129,0.3910,-0.5303,0.1503,0.6674,-1.3833,0.4492,0.4633,-0.5158,-1.2119,0.4361,-1.2354,1.8686,0.5841,0.2872,-1.3090,-1.7143,-0.4777,0.5786,0.0833,-1.2428,1.4114,0.2156
MB-0008,-2.0498,-1.2677,-0.8829,-0.9718,-0.0172,2.0533,-0.4041,-0.5587,0.3816,1.3112,0.5532,-0.3265,-1.0231,1.3849,-1.2209,1.4937,2.1953,-0.3081,-0.0856,-0.1730,-1.0259,0.0386,-0.4131,0.4132,-1.4403,...,0.2345,-1.6906,0.7067,2.1183,0.7117,0.9831,-0.1455,0.5056,-1.9579,-0.1229,-1.5196,-1.3287,-0.1299,-2.0595,0.3220,1.0591,0.6851,-1.3606,-0.2123,-0.3088,-0.0857,1.5561,-1.0884,-1.3529,-1.2238

In [7]:
df_merged = pd.merge(
    df_cna.rename(columns=lambda s: "df_cna-" + s),
    df_methylation_promoters_rrbs.rename(
        columns=lambda s: "df_methylation_promoters_rrbs-" + s
    ),
    how="outer",
    left_index=True,
    right_index=True,
)

df_merged = pd.merge(
    df_merged,
    df_mrna_agilent_microarray.rename(
        columns=lambda s: "df_mrna_agilent_microarray-" + s
    ),
    how="outer",
    left_index=True,
    right_index=True,
)

df_merged.head()

Hugo_Symbol,df_cna-A1BG,df_cna-A1BG-AS1,df_cna-A1CF,df_cna-A2M,df_cna-A2M-AS1,df_cna-A2ML1,df_cna-A2MP1,df_cna-A3GALT2,df_cna-A4GALT,df_cna-A4GNT,df_cna-AAAS,df_cna-AACS,df_cna-AACSP1,df_cna-AADAC,df_cna-AADACL2,df_cna-AADACL3,df_cna-AADACL4,df_cna-AADAT,df_cna-AAED1,df_cna-AAGAB,df_cna-AAK1,df_cna-AAMDC,df_cna-AAMP,df_cna-AANAT,df_cna-AAR2,...,df_mrna_agilent_microarray-TMEM146,df_mrna_agilent_microarray-SLIT3-AS1,df_mrna_agilent_microarray-PSMC3IP,df_mrna_agilent_microarray-TEAD1,df_mrna_agilent_microarray-LOC253724,df_mrna_agilent_microarray-BM725158,df_mrna_agilent_microarray-GRHPR,df_mrna_agilent_microarray-EGLN2,df_mrna_agilent_microarray-TBC1D4,df_mrna_agilent_microarray-ANGPTL2,df_mrna_agilent_microarray-AF086457,df_mrna_agilent_microarray-AK124197,df_mrna_agilent_microarray-ENOX1,df_mrna_agilent_microarray-SBF2-AS1,df_mrna_agilent_microarray-VN1R4,df_mrna_agilent_microarray-BX115874,df_mrna_agilent_microarray-BX107598,df_mrna_agilent_microarray-UGCGL1,df_mrna_agilent_microarray-VPS72,df_mrna_agilent_microarray-CSMD3,df_mrna_agilent_microarray-CC2D1A,df_mrna_agilent_microarray-CB986545,df_mrna_agilent_microarray-IGSF9,df_mrna_agilent_microarray-DA110839,df_mrna_agilent_microarray-FAM71A
MB-0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.353135,5.198876,5.901473,5.610397,5.515762,5.213511,8.139151,10.232505,7.311327,9.677952,5.318426,5.635153,5.918239,5.295203,5.474224,5.329883,5.745324,7.021679,8.010657,5.299815,6.235804,5.349555,5.947404,5.615147,5.133576
MB-0002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,-1.0,-1.0,0.0,...,4.888335,5.615278,6.447777,5.950548,5.502117,5.124030,8.261487,10.186566,6.324112,8.895600,5.345262,6.281727,5.515844,5.442257,5.303871,5.384794,5.285060,7.612797,7.988643,5.194247,6.328059,5.469445,6.938685,5.231857,5.604560
MB-0005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,5.313808,5.508167,6.076896,5.747801,5.368297,5.371385,7.731911,9.954702,7.222594,8.972083,5.420388,5.404494,5.350242,5.368716,5.370394,5.336455,5.452393,6.619220,8.044471,5.306294,6.306927,5.362207,7.397672,5.372138,5.645597
MB-0006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,5.228991,5.324400,5.650472,5.579526,5.303998,5.351482,8.301195,10.088769,7.053031,8.664307,5.370416,5.480761,5.650978,5.295628,5.694697,5.663304,5.529928,6.966482,7.527300,5.197607,6.515638,5.309927,6.175716,5.586521,5.354582
MB-0008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.322069,5.136661,6.403137,5.904885,5.473140,5.460753,8.007261,11.244345,5.926732,8.141539,5.217030,5.442109,5.527755,5.192858,5.474929,5.799346,5.597297,6.942461,8.115359,5.254136,6.323751,5.518767,6.272568,5.204630,5.030636

In [ ]:
# Visualization of missing data
fig, ax = plt.subplots(figsize=(15, 8))
sns.heatmap(
    df_merged.isnull(),
    yticklabels=False,
    cbar=False,
    cmap="viridis",
)
ax.set_title("Main Data Frame")
plt.show();